In [1]:
#allow output from every line
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np

In [9]:
# 2 - Choose a league, season, and 4 teams within the league. For the given season, collect the roster
#table from sports reference for ALL 4 teams. This should result in you having 4 different CSVs
#(one for each team).

    #I decided to select the Detroit Red Wings, Boston Bruins, Philadelphia Flyers, & Tampa Bay Lightning from
    # 23-24 NHL season.

# 3 - In your notebook file, read all 4 CSVs in, with the index being the player name.

red_wings_roster = pd.read_csv("Red_Wings_Roster.csv", index_col='Player')
bruins_roster = pd.read_csv("Bruins_Roster.csv", index_col='Player')
flyers_roster = pd.read_csv("Flyers_Roster.csv", index_col='Player')
lightning_roster = pd.read_csv("Lightning_Roster.csv", index_col='Player')

In [14]:
# 4 - Concatenate the 4 tables into 1 all-inclusive table.

four_hockey_rosters = pd.concat([red_wings_roster, bruins_roster, flyers_roster, lightning_roster], ignore_index=False)
four_hockey_rosters

,No.,Flag,Pos,Age,Ht,Wt,S/C,Exp,Birth Date,Summary,Salary,Draft,Player-additional
Player,,,,,,,,,,,,,
Ben Chiarot,8,ca,D,32,3-Jun,224,L/-,10,May 9 1991,3 G 9 A 12 P,"$5,250,000",2009 ATL 4th (120),chiarbe01
J.T. Compher,37,us,F,28,Jun-00,190,R/-,7,April 8 1995,11 G 18 A 29 P,"$5,500,000",2013 BUF 2nd (35),comphj.01
Andrew Copp,18,us,F,29,1-Jun,203,L/-,9,July 8 1994,10 G 14 A 24 P,"$6,250,000",2013 WPG 4th (104),coppan01
Alex DeBrincat,93,us,F,26,8-May,180,R/-,6,December 18 1997,18 G 25 A 43 P,"$8,250,000",2016 CHI 2nd (39),debrial01
Robby Fabbri,14,ca,F,28,1-Jun,185,L/-,7,January 22 1996,13 G 8 A 21 P,"$4,250,000",2014 STL 1st (21),fabbrro01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Darren Raddysh,43,ca,D,27,1-Jun,200,R/-,2,February 28 1996,4 G 16 A 20 P,"$775,000",NaN,raddyda01
Conor Sheary,73,us,F,31,9-May,179,L/-,8,June 8 1992,1 G 8 A 9 P,"$1,500,000",NaN,shearco01
Steven Stamkos (C),91,ca,F,33,Jun-00,182,R/-,15,February 7 1990,22 G 26 A 48 P,"$1,000,000",2008 TBL 1st (1),stamkst01
Andrei Vasilevskiy,88,ru,G,29,4-Jun,220,-/L,9,July 25 1994,17-11-0 2.79 GAA,"$4,000,000",2012 TBL 1st (19),vasilan02
Austin Watson,51,us,F,32,4-Jun,204,R/-,9,January 13 1992,2 G 1 A 3 P,"$776,665",2010 NSH 1st (18),watsoau01

In [15]:
four_hockey_rosters.to_csv("DET_BOS_PHI_TAM_Rosters.csv")